export declare enum HttpStatus {
    BAD_REQUEST = 400,
    UNAUTHORIZED = 401,
    FORBIDDEN = 403,
    NOT_FOUND = 404,
    CONFLICT = 409,
    UNPROCESSABLE_ENTITY = 422,
    INTERNAL_SERVER_ERROR = 500
}
export declare enum ErrorCode {
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
    ACCESS_TOKEN_REQUIRED = "ACCESS_TOKEN_REQUIRED",
    REFRESH_TOKEN_REQUIRED = "REFRESH_TOKEN_REQUIRED",
    INVALID_TOKEN = "INVALID_TOKEN",
    TOKEN_EXPIRED = "TOKEN_EXPIRED",
    INVALID_PASSWORD = "INVALID_PASSWORD",
    INVALID_RESET_TOKEN = "INVALID_RESET_TOKEN",
    EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED",
    USER_EXISTS = "USER_EXISTS",
    USER_NOT_FOUND = "USER_NOT_FOUND",
    VALIDATION_ERROR = "VALIDATION_ERROR",
    DATABASE_ERROR = "DATABASE_ERROR",
    INTERNAL_ERROR = "INTERNAL_ERROR",
    NOT_FOUND = "NOT_FOUND",
    EMAIL_SEND_FAILED = "EMAIL_SEND_FAILED",
    UNEXPECTED_ERROR = "UNEXPECTED_ERROR",
    NETWORK_ERROR = "NETWORK_ERROR",
    INVALID_JSON = "INVALID_JSON"
}
//# sourceMappingURL=errors.d.ts.map