// Standard HTTP status codes for API errors
export enum HttpStatus {
  // not errors but, keep them for now >_<
  OK = 200,
  CREATED = 201,
  ACCEPTED = 202,
  NO_CONTENT = 204,

  // errors
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  CONFLICT = 409,
  UNPROCESSABLE_ENTITY = 422,
  INTERNAL_SERVER_ERROR = 500,
  REQUEST_TIMEOUT = 408,
}

// Application-specific error codes
export enum ErrorCode {
  // Authentication & Authorization
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  ACCESS_TOKEN_REQUIRED = 'ACCESS_TOKEN_REQUIRED',
  INVALID_ACCESS_TOKEN = 'INVALID_ACCESS_TOKEN',

  REFRESH_TOKEN_REQUIRED = 'REFRESH_TOKEN_REQUIRED',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',

  INVALID_TOKEN = 'INVALID_TOKEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  INVALID_RESET_TOKEN = 'INVALID_RESET_TOKEN',
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',

  INVALID_JSON = 'INVALID_JSON',

  ALREADY_EXISTS = 'ALREADY_EXISTS',

  // User Management
  USER_EXISTS = 'USER_EXISTS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',

  // Validation
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  // Database
  DATABASE_ERROR = 'DATABASE_ERROR',

  // Generic
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  NOT_FOUND = 'NOT_FOUND',

  // Email
  EMAIL_SEND_FAILED = 'EMAIL_SEND_FAILED',

  // Unexpected
  UNEXPECTED_ERROR = 'UNEXPECTED_ERROR',

  NETWORK_ERROR = 'NETWORK_ERROR',
  TIMEOUT = 'TIMEOUT',

  // Block-related
  DUPLICATE_ORDER = 'DUPLICATE_ORDER',
  INVALID_PARENT_ID = 'INVALID_PARENT_ID',

  // Permissions
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  PERMISSION_ASSIGNMENT_FAILED = 'PERMISSION_ASSIGNMENT_FAILED',
}
